exclude: "third_party"
repos:
  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: python
      types_or: [c++, c]
      args: [-style=file, -i]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 516a8a263c137b51b43f01cbd5441f735390363e
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
